import {spawnSync} from 'node:child_process';
import {readFileSync, readdirSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const root = fileURLToPath(new URL('../..', import.meta.url));
const result = spawnSync('cargo', ['metadata', '--locked', '--format-version', '1'], {cwd:root, encoding:'utf8', maxBuffer:16 * 1024 * 1024, timeout:120000});
if (result.status !== 0) throw new Error(result.stderr || String(result.error));
const metadata = JSON.parse(result.stdout);
const parentWinapi = metadata.packages.find(pkg => pkg.name === 'winapi' && pkg.version === '0.3.9');
let text = 'Third-party license inventory generated by scripts/packaging/notices.mjs from the locked Cargo dependency graph.\nNot every target-specific package is linked into every binary.\n';
for (const pkg of metadata.packages.filter(pkg => pkg.name !== 'terminal-rtl').sort((a,b) => `${a.name} ${a.version}`.localeCompare(`${b.name} ${b.version}`, 'en'))) {
  let directory = dirname(pkg.manifest_path);
  let note = '';
  // The published import-library crates omit license files. They declare the
  // same dual license and upstream repository as winapi; include its texts.
  if (/^winapi-(i686|x86_64)-pc-windows-gnu$/.test(pkg.name)) {
    if (!parentWinapi || pkg.repository !== parentWinapi.repository) throw new Error(`Review license source for ${pkg.name}`);
    directory = dirname(parentWinapi.manifest_path);
    note = '\nImport-library license texts from winapi 0.3.9 (same upstream repository); the import crate declares MIT/Apache-2.0.\n';
  }
  const files = readdirSync(directory, {withFileTypes:true}).filter(entry => entry.isFile() && /^(licen[cs]e|copying|notice|unlicense)/i.test(entry.name)).map(entry => entry.name).sort();
  if (pkg.license_file && !files.includes(pkg.license_file)) files.push(pkg.license_file);
  if (!files.length) throw new Error(`Missing license texts: ${pkg.name} ${pkg.version}`);
  text += `\n\n=== ${pkg.name} ${pkg.version} (${pkg.license || 'see license file'}) ===\n${note}`;
  for (const file of files) text += `\n${file}\n\n${readFileSync(join(directory,file),'utf8').replace(/\r\n/g,'\n').trimEnd()}\n`;
}
text += '\nLocal parser modifications: see vendor/vt100/PATCHES.md and vendor/vte/PATCHES.md.\n';
const target = join(root, 'THIRD_PARTY_LICENSES.txt');
if (process.argv.includes('--write')) writeFileSync(target,text);
else if (readFileSync(target,'utf8').replace(/\r\n/g,'\n') !== text) throw new Error('Third-party notices are stale; run node scripts/packaging/notices.mjs --write and review the changes.');
console.log(`Verified notices for ${metadata.packages.length - 1} locked dependency packages.`);
